### ISSUE TITLE
Having issues calling applyMiddleWare

### ISSUE THREAD

**Issue by osayame** [gaearon/redux-thunk#71]
Hi there:

I am having issues when creating a store with redux-thunk as middleware.

Here's the error message:

> ERROR in ./web/static/js/index.js
Module build failed: SyntaxError: /Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/web/static/js/index.js: Unexpected token (17:34)
  15 |   combineReducers({
  16 |     rootReducer,
> 17 |     applyMiddleware(...ReduxThunk),
     |                                   ^
  18 |     routing: routerReducer
  19 |   })
  20 | )
    at Parser.pp.raise (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.expect (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/util.js:83:33)
    at Parser.pp.parseBlock (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/statement.js:509:8)
    at Parser.pp.parseFunctionBody (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:913:22)
    at Parser.parseFunctionBody (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/plugins/flow.js:17:20)
    at Parser.pp.parseMethod (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:882:8)
    at Parser.pp.parseObjPropValue (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:799:10)
    at Parser.parseObjPropValue (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/plugins/flow.js:298:13)
    at Parser.pp.parseObj (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:777:10)
    at Parser.pp.parseExprAtom (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:486:19)
    at Parser.parseExprAtom (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
    at Parser.pp.parseExprSubscripts (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExprListItem (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:1032:16)
    at Parser.parseExprListItem (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/plugins/flow.js:215:24)
    at Parser.pp.parseCallExpressionArguments (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:348:20)
    at Parser.pp.parseSubscripts (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:311:31)
    at Parser.pp.parseExprSubscripts (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:282:15)
    at Parser.pp.parseMaybeUnary (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExprListItem (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:1032:16)
    at Parser.parseExprListItem (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/plugins/flow.js:215:24)
    at Parser.pp.parseCallExpressionArguments (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:348:20)
    at Parser.pp.parseSubscripts (/Users/osayame/Dropbox/osayame/Work/Luma/repos/luma-command-center/node_modules/babylon/lib/parser/expression.js:311:31)
 @ multi main

Here's the code in question:

> import 'babel-core/register';
import ReactDOM from 'react-dom';
import React from 'react';
import { createStore, combineReducers, applyMiddleware } from 'redux';
import { Router, Route, browserHistory } from 'react-router';
import { Provider } from 'react-redux';
var ReduxThunk = require('redux-thunk').default
import { syncHistoryWithStore, routerReducer } from 'react-router-redux';
import rootReducer from './reducers/index';
import routes from './routes';
import "../css/index.css";
const store = createStore(
  combineReducers({
    rootReducer,
    applyMiddleware(...ReduxThunk),
    routing: routerReducer
  })
)
const history = syncHistoryWithStore(browserHistory, store)
const rootElement = document.getElementById('root');
ReactDOM.render(
  <Provider store={store}>
    <Router children={routes} history={history} />
  </Provider>,
  document.getElementById('root')
);

**Comment by osayame** [comment]
I was writing my createStore call incorrectly.

Should have been:

> const store = createStore(
  combineReducers({
    rootReducer,
    routing: routerReducer
  },
  applyMiddleware(ReduxThunk))
)
